---
  - name: "Playing with Ansible and Git"
    hosts: 127.0.0.1
    become: true
     
    tasks:
     - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
       copy:
          content: hello worldn
          dest: /home/gigatorb/Desktop
     - debug: var=output.stdout_lines
         
      
        
