---
  - name: "Playing with Ansible and Git"
    hosts: 127.0.0.1
    connection: local
    become: yes
    become_user: gigatorb
    tasks:

     - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
       copy:
          content: hello worldn
          dest: /home/gigatorb/OASDemo/OASZIP/testfile.txt

     - debug: var=output.stdout_lines
      
        
