---
  - name: "Playing with Ansible and Git"
    hosts: localhost
    connection: local 
    become: yes
    become_user: root
    become_method: sudo
    tasks:

     - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
       copy:
          content: hello worldn
          dest: /home/gigatorb/OASDemo/OASZIP/testfile.txt

     - debug: var=output.stdout_lines
      
        
